#!/bin/sh
# initialize rootlesskit for CDI
cdi_init_rootless(){
  test -f $HOME/bin/dockerd-rootless.sh || throw rootless dockerd not found
  $HOME/bin/dockerd-rootless.sh --experimental --storage-driver=btrfs
}
