#!/bin/sh

#preinvoke_raw $core 
#invoke_raw $core || { echo "error" >&2; exit 1;}
#  docker exec -dt -e http_proxy=http://squid.cosh:3128 -u root ${core:-coremate} apt-get install -y pulseaudio || exit 1

pod_pkg_init(){
  showdesc(){ echo "pkg_init CONNAME PKGNAME" >&2; exit 1;}
  : ${1:? pkg_init: container name not specifies!} || showdesc
  : ${2:? pkg_init: package name not specifies!} || showdesc

  case "$1" in
    dom0|gnome)
      pudo docker exec -dt -u root $1 apt-get remove -y $2 || exit 1
      pudo docker exec -dt -u root $1 apt-get install -y $2 || exit 1
      ;;
    archlinux)
      #docker exec -dt -u root ${1} pacman -R $2 || exit 1
      #docker exec -dt -u root ${1} pacman -S $2 || exit 1
      : ;;
  esac
}
