#!/bin/sh
# initialize Dom1 container as rootless in docker
rind_init(){
  #network_connect 10.11.11.11 cdi_system dom1 
  #network_connect 10.111.111.11 cdi_open dom1 
  pudo docker exec -dt ${1:?@cdictl/rind_init: container name not specified!} dockerd-rootless.sh --experimental --host ${CDI_RIND_HOST:?rind_init: CDI_RIND_HOST not set!} --storage-driver=btrfs
}
