FROM coshapp/admin:debian-l10n-ja-10.5

USER root
RUN usermod -aG sudo duser
RUN echo 'duser ALL=(ALL) NOPASSWD: /usr/bin/docker *' | tee -a /etc/sudoers
RUN echo '127.0.0.2 dom0.cosh' >> /etc/hosts
RUN apt-get install -y vim git

USER duser 
RUN sudo docker help version || exit 1
WORKDIR /home/duser

RUN mkdir -p local/shef
WORKDIR /home/duser/local/shef
RUN git config --global user.name saru
RUN git config --global user.email okadas@dev.sysnk.net

RUN git clone https://github.com/okadash/shef /home/duser/local/shef
WORKDIR /home/duser/local/shef
RUN ./install.sh || cp -av bin/shef /home/duser/.shef/bin 
ENV PATH=/home/duser/.shef/bin:$PATH
ENV EDITOR=/usr/bin/vim
RUN shef install https://github.com/okadash/cosh-transitional
RUN shef install https://github.com/okadash/nik-transitional

CMD /bin/sh
