FROM coshapp/admin:debian-l10n-ja-10.5

USER root
RUN echo '127.0.0.2 dom0.cosh' | tee -a /etc/hosts
RUN apt-get install -y vim git
RUN cp -v /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
RUN mkdir -vp /run/user/1000
RUN chown 1000:1000 /run/user/1000
RUN usermod -aG sudo duser
RUN echo 'duser ALL=(ALL) /usr/bin/docker *' | tee -a /etc/sudoers

USER duser 
RUN sudo docker help version || exit 1
WORKDIR /home/duser

RUN mkdir -p local/shef
WORKDIR /home/duser/local/shef
RUN git config --global user.name saru
RUN git config --global user.email okadas@dev.sysnk.net

ADD . /home/duser/.shef
ENV PATH=/home/duser/.shef/bin:$PATH
ENV TZ=Asia/Tokyo

CMD /bin/sh
