#!/bin/sh

cdi_network_launch(){
  network_exist cdi_internal || INTERNAL=1 network_create 10.10.10.0/24 cdi_internal
  network_exist cdi_open || ATTACHABLE=1 network_create 10.111.111.0/24 cdi_open
  network_exist cdi_system || network_create 10.11.11.0/24 cdi_system
}

cdi_network_remove(){
  for i in cdi_internal cdi_open cdi_system; do
    network_remove $i
  done
}
