#!/bin/sh
cdi_launch(){
  vol_args=
  dev_args=
  env_args=
  cdi_setenv ${1:?cdi_launch: argument needed!};
  docker run --rm --name ${con_name:?container name not specified!} -dt \
    $vol_args $dev_args $env_args $net_args ${img_name:?image name not specified!} sh -c "${cmd_args:-while :; do sleep 1000000; done}"

}

cdi_remove(){
  docker stop $1 &
}
