#!/bin/sh
cdi_up(){
  cdi_network_launch
  for i in ${CDI_RIND:+dom1} ${CDI_CORE:-dom0} ${@:+$@ px}; do 
    pod_launch $i; 
    test $i = px && network_connect 10.11.11.11 cdi_system px
  done

  if test -z "$CDI_ROOTLESS"; then 
    test ! -z "$CDI_WITH_PA" && {
      pod_pkg_init ${CDI_CORE} pulseaudio
      pod_pkg_init ${CDI_CORE} docker.io
    }
  fi
  ${CDI_RIND:+rind_init dom1}
}
