#!/bin/sh

cdi_chknetwork(){
  docker network ls | grep ${1:?cdi_chknetwork: argument needed!} > /dev/null && return 0 || return 1
}

cdi_network_launch(){
  cdi_chknetwork cdi_internal || docker network create --subnet=10.110.101.0/24 cdi_internal
  cdi_chknetwork cdi_open || docker network create --subnet=10.111.101.0/24 cdi_open
  cdi_chknetwork cdi_system || docker network create --subnet=10.111.111.0/24 cdi_system
}

cdi_network_remove(){
  cdi_chknetwork cdi_internal && docker network remove cdi_internal
  cdi_chknetwork cdi_open && docker network remove cdi_open
  cdi_chknetwork cdi_system && docker network remove cdi_system

}
